[package]
name = "tempo-storage-interop"
version = "0.8.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
alloy-primitives = "1.5.0"
thiserror = "2.0.14"

[dev-dependencies]
proptest = "1.7"
